### PR TITLE
Sample async file handler

### PR DESCRIPTION
**Pull request by mkhon**
- Sample async file handler. Build with -DASYNC_FILE_HANDLER to build async file handler.
- Use pread/pwrite instead of lseek+read/write.

### CODE REVIEW

**Comment by mkhon** [comment]
I submitted separate pull request for pread/pwrite (see #29). Will merge/rebase it once it gets in.

**Comment by agrover** [comment]
it might be clearer if we have the async file handler example be separate from the sync file handler example, what do you think?

**Comment by os12** [comment]
How about building two `.so` files from the same source? Both are file handlers, both conform to the Runner's API...

P.S. is this even possible with CMake?

**Comment by agrover** [comment]
I was really focusing on file_example.c as a code sample for handler writers rather than something that anyone would ever use. For actual use, the in-kernel fileio backstore should be strictly better. An async example would also be great, and I was thinking easier to understand if a developer could compare the async vs sync implementations side-by-side. The only issue would be we'd need to keep both of them up to date if other API changes happened.

**Comment by mkhon** [comment]
Andy,

This code change does not have any practical use except testing async handler code paths and was not intended as a replacement for in-kernel file backend in any way. There's a lot of code shared between sync and non-async so I would suggest either having an ifdef (like now) or split them into common source file and two handler stubs. What do you think?

**Comment by agrover** [comment]
ok, ifdefs are fine.

**Comment by mkhon** [comment]
I updated the pull request with the latest code and changes as discussed above.

**Comment by agrover** [comment]
Thanks!

**Pull request merged**
