### PR TITLE
Factored out SCSI request processing

### PR DESCRIPTION
**Pull request by os12**
Today, tcmu-runner owns the worker threads, thus forcing the users' code into the
plugin structure. This certainly works for minimal examples, but prevents any kind
of embedding into larger 3rd-party applications.

Production-grade applications generally have their own threading structure and want
to deal with socket/file/tcmu notifications in an async way. As such, I just need a
minimal library that handles device opening and command parsing.

There are several API sets now:
 - the API each plugin must implement (unchanged, see tcmu_handler)
 - the API available to the plugin (api.c)
 - the API the host process must implement (debug functions today)
 - the minimal API tcmu_lib will provide (a new concept, builds on api.c)

### CODE REVIEW

**Comment by os12** [comment]
Hi Andy, thank you for the quick review!

I've corrected the issues you have pointed out to date, rewritten the patches and pushed again.

**Comment by os12** [comment]
BTW, here are a few notes from the PR's first generation, for the record. The rest of the comments have been addressed and patches have been rewritten.

### Static/shared library

Indeed, shipping a `.so` file is possible.

However, the large C++ applications I have worked with build their entire world of dependencies from scratch to avoid API/ABI issues (imagine mixing compiler versions that ship different STL versions). As such, producing a static lib is perfectly fine and simplifies binary distribution a little. (Also, AFAIK, the C ABI on Linux is pretty stable anyway, so building out of the tree should work too).

Case in point, I've added tcmu-runner as a git module and build the static lib together with the hosting app.

### Logging support

The hosting app must implement the following API:

    void dbgp(const char *fmt, ...);
    void errp(const char *fmt, ...);

Consider a bigger application with its own log system: log files, rotation, levels, paths, redirection etc. Suppressing or dumping information to stderr/stdout is not useful in such a system.

Specifically, in my system, these C-style calls are routed to the main C++-style log subsystem with an appropriate path and severity.

**Comment by agrover** [comment]
Ok, I guess as long as both static and shared are possible there's no issue.

About dbgp/errp, I see your point, I just don't like the the main application having to export specific symbols. But I think this is fine for now and we can merge this and explore different possibilities with this as a base.

Thanks for your work! :+1:

**Comment by os12** [comment]
Great! Thanks, Andy!

P.S. the C-style debug function pointers can be passed into the `init_tcmu_lib()` function. We'll need to look into the API extensions as part of #12.

**Comment by agrover** [comment]
Cool, that's what I was thinking.

I'm going to add you as a collaborator. Please continue to use PRs for significant changes, and I will start doing the same.

**Comment by os12** [comment]
Cool, thanks!

BTW, opening PRs is the nicest way irrespective of the rights, as there 
a nice web trail (with discussion) and people who watch the repo get 
notified of changes.

**Pull request merged**
